name: Deploy Mealzaar

on:
  push:
    branches:
      - main  # change if your branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts

    - name: Deploy files to server
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        scp -i ~/.ssh/id_ed25519 -r ./ "$VPS_USER"@"$VPS_HOST":/var/www/mealzaar/

    - name: Restart Nginx (optional)
      env:
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_USER: ${{ secrets.VPS_USER }}
      run: |
        ssh -i ~/.ssh/id_ed25519 "$VPS_USER"@"$VPS_HOST" 'sudo systemctl restart nginx'
